# Generated by Django 4.2.7 on 2023-12-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0004_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=models.TextField(max_length=500),
        ),
    ]
