# Generated by Django 4.2.7 on 2023-12-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0005_alter_post_cuerpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lugares',
        ),
        migrations.DeleteModel(
            name='Restaurantes',
        ),
    ]
