# Generated by Django 4.2.7 on 2023-12-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercustom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCustom',
        ),
    ]
